language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t xelnagah/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xelnagah/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-796957094383"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: "$AWS_SECRET_KEY"